### ISSUE TITLE
unable to extend ga_sessions or ga_sessions_core

### ISSUE THREAD

**Issue by wsjk** [llooker/ga_360_new#2]
Having issues extending ga_sessions or ga_sessions_core Explore in our project because we can't reference the Explores without including the google_analytics_360.model.lkml file.

Wondering if ga_sessions and ga_sessions_core could be defined in its ga_sessions.explore file to help with this.

**Comment by AnnaSerova** [comment]
This was addressed in https://github.com/llooker/ga_360_new/commit/abef5a4fe5674852107e9d712e82e9e88c4254e3
