### ISSUE TITLE
GA4 data?

### ISSUE THREAD

**Issue by ghost-writer-hub** [llooker/ga_360_new#3]
Hi, is there any way we can adapt all the work done here to read GA4 events instead of GA360 ones?

**Comment by KalchoEPAM** [comment]
Hey anyone managed to link this ML to GA4 data instead of GA360?

**Comment by ghost-writer-hub** [comment]
I haven't :(

**Comment by KalchoEPAM** [comment]
Hi Carlos,
Here is update on my end - i found prebuild module for installation on the Looker Market - yourorganizationdomain.looker.com/marketplace/view/ga4 this will allow you to consume your GA4 data if you already have linked it in BigQuery

**Comment by ghost-writer-hub** [comment]
Whoa!! this is super useful! Many thanks
